# Generated by Django 5.2.1 on 2025-05-11 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pad_number', models.CharField(max_length=50)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('one_month_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('one_month_advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_water_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_electric_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_electric_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_water_reading', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('date_occupancy', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='payrent.room')),
            ],
        ),
    ]
