# Generated by Django 5.2.1 on 2025-06-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrent', '0004_smslog_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='username',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
